### ISSUE TITLE
Object nInput_CBPMRunningFlows.js, function ow.waf.cbpm.listFlows is giving out error JavaException: wedo.jaf.protocols.xdt.XDTClientException: Error during remote execution -> Unknown parameter "loadExecutionData"

### ISSUE THREAD

**Issue by abrizida** [OpenAF/nAttrMon#212]
**Describe the bug**
When adding the Input 03.flows.yaml this error appears in the log and the input is not loaded.
![image](https://github.com/OpenAF/nAttrMon/assets/33725785/e0ce40fd-93b1-4789-a34c-3ebc7432df8d)

**To Reproduce**
1. cp the file 03.flows.yaml from inputs.disabled to inputs folder
2. stop and start nAttrMon
3. Check the nattrmon.log file

**Additional context**
The issue is with function ow.waf.cbpm.listFlows.
Trying in a openaf console I got the same error:
![image](https://github.com/OpenAF/nAttrMon/assets/33725785/a2ed5c50-edbe-4c4a-896e-982c9404ed53)

**Comment by nmaguiar** [comment]
Seems there are two new parameters required to list CBPM flows on newer RAID versions: loadExecutionData and escapedSearch. Changed that in OpenCli.

**Comment by nmaguiar** [comment]
Fixed ow.waf.cbpm.listFlows (and also ow.waf.bpmn.listFlows) is now available on the OpenCli 20231014 stable.
