### ISSUE TITLE
Avoid "/" on semaphore names in nInput_Semaphores and nInput_CBPMSemaphores

### ISSUE THREAD

**Issue by nmaguiar** [OpenAF/nAttrMon#41]
On nInput_Semaphores and nInput_CBPMSemaphores if a semaphore name has one or more "/" it will be interpreted as a sub-folder/sub-category. The names should be replaced by another character like "_".

**Comment by abrizida** [comment]
On the construction of the attribute name for the Input replace the "/" with "_" on the Semaphore name / description.
