### ISSUE TITLE
ElasticSearch Weekly index

### ISSUE THREAD

**Issue by hdiass** [OpenAF/nAttrMon#67]
For better or more flexible ,index management on ElasticSearch , a feature that enables us to choose to use a daily , weekly and maybe monthly index creation.

**Comment by nmaguiar** [comment]
As you can see on the example https://github.com/OpenAF/nAttrMon/blob/master/config/outputs.disabled/js/05.es.log.js it's possible to provide a function (using funcIndex) to build the index name where you can specify day, week, month, etc...  
We could add a 'format' argument to use the ow.ch.utils.getElasticIndex function automatically (if funcIndex is not provided).
